### ISSUE TITLE
Wtf ?!

### ISSUE THREAD

**Issue by DavidFrancois** [Shenrak/neKo#1]
Where is the code ? Where are the specs ?

Is this just one more empty repo or did you just want to write some Markdown ?!!!!!

**Comment by Shenrak** [comment]
**Markdown** is _coming_ !!
Readme will be edited soon, no worries
I hope i'll soon get my partner to code 👍 
:)

**Comment by DavidFrancois** [comment]
Damn emo-partners ...

**Comment by loicmarne** [comment]
Stupid boys

**Comment by ViGrad** [comment]
Emo is so good guy
