### ISSUE TITLE
Let's do some real stuff

### ISSUE THREAD

**Issue by justinrlle** [Shenrak/neKo#4]
I have a few thoughts on the organisation of this project, but first, let me ask some questions:
* Why is __neKoApi__ in a separate folder? Is it because it won't serve the website itself? Because differents frontends could be used, like a desktop app or a mobile app?
* What are your plans for the website?
* Are you really serious with this project?

Anyway, here are my recommendations for this project:
* If __neKpoApi__ is indeed separated from the frontend, then it _should be_ in another repo. Usually, the package.json should be _at the root of the repository_, this ain't some shitty eclipse workspace you know.
* Add some _linting_. I can work on this one, like adding a config for [eslint](http://eslint.org), or using some configuration-less linter (like [standard](http://standardjs.com/) or [xo](https://github.com/sindresorhus/xo)), and adding some git hooks to lint files before commits.
* Use __*es2015*__. No `var`, no `for..in`, use some _real features_ like `let` and `const` (which are block hoisted, like in _any language_, in opposition to `var` which is a **huge** mess), or `for..of` loops, `Array.map()`, `Array.filter()`, `Array.each()`, `Array.reduce()`...
* A better workflow, or at least a _more documented_ one. Saying just _"please contribute!"_ won't be enough.

**Comment by Shenrak** [comment]
Hello,

* As you said, we want to **separate** Back-end from Front-end to support mobile app and desktop app.
* We do want to create a chat that'll hold some features that ourselves find **missing** in common chat apps, plus maybe add some git features for developpers
* Of course, we're serious

---- 

Thank you for your advices, we certainly will take in line.

:)

**Comment by justinrlle** [comment]
Hey, don't close the discussion like that
