### ISSUE TITLE
Reorganize the repo

### ISSUE THREAD

**Issue by justinrlle** [Shenrak/neKo#6]
The root of the repo __should be__ where you put the `package.json`.

If you want mobile apps, and different front ends, you'll do them in __different git repos__, because they are __different projects__.

If you want a place to _explain_ what is neKo, you'll use something like [Github Pages](https://pages.github.com/) (_TL;DR: **static** website **freely** hosted by Github where everything is written in **markdown**_).

Use the _right_ tool at the _right_ place, and in the _right_ way, please.

---

So, @Shenrak, @4kakarendset, are you on this one?

**Comment by Shenrak** [comment]
Ok, you got me here.
Maybe it's a little too early to go on [Github Pages](https://pages.github.com/), but I admit that I'm a little unexperienced.
I'll change the path to the API

**Comment by justinrlle** [comment]
Okay, I'll be watching for the change to work on #5

**Comment by Shenrak** [comment]
Refactoring done
